name: mainline-alpine

on:
  push:
    branches:
      - main  
    tags:
      - '*'
  workflow_dispatch:
jobs:
    buildx:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v4
        -
          # Add support for more platforms with QEMU (optional)
          # https://github.com/docker/setup-qemu-action
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}          
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: Dockerfile.alpine
            platforms: linux/ppc64le
            push: true
            build-args: |
                NGINX_FROM_IMAGE=nginx:1.25.2-alpine
                ENABLED_MODULES=brotli headers-more modsecurity geoip2 subs-filter
            tags: |
                snowdreamtech/nginx:1.25.2-alpine
                snowdreamtech/nginx:mainline-alpine
                snowdreamtech/nginx:1-alpine
                snowdreamtech/nginx:1.25-alpine
                snowdreamtech/nginx:alpine
                snowdreamtech/nginx:1.25.2-alpine3.18
                snowdreamtech/nginx:mainline-alpine3.18
                snowdreamtech/nginx:1-alpine3.18
                snowdreamtech/nginx:1.25-alpine3.18
                snowdreamtech/nginx:alpine3.18             
                ghcr.io/snowdreamtech/nginx:1.25.2-alpine
                ghcr.io/snowdreamtech/nginx:mainline-alpine
                ghcr.io/snowdreamtech/nginx:1-alpine
                ghcr.io/snowdreamtech/nginx:1.25-alpine
                ghcr.io/snowdreamtech/nginx:alpine
                ghcr.io/snowdreamtech/nginx:1.25.2-alpine3.18
                ghcr.io/snowdreamtech/nginx:mainline-alpine3.18
                ghcr.io/snowdreamtech/nginx:1-alpine3.18
                ghcr.io/snowdreamtech/nginx:1.25-alpine3.18
                ghcr.io/snowdreamtech/nginx:alpine3.18