name: stable-perl

on:
  push:
    branches:
      - main  
    tags:
      - '*'
  workflow_dispatch:
jobs:
    buildx:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v4
        -
          # Add support for more platforms with QEMU (optional)
          # https://github.com/docker/setup-qemu-action
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}          
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: Dockerfile
            platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
            push: true
            build-args: |
                NGINX_FROM_IMAGE=nginx:1.24.0-perl
                ENABLED_MODULES=brotli headers-more modsecurity geoip2 subs-filter
            tags: |
                snowdreamtech/nginx:1.24.0-perl
                snowdreamtech/nginx:stable-perl
                snowdreamtech/nginx:1.24-perl
                snowdreamtech/nginx:1.24.0-bullseye-perl
                snowdreamtech/nginx:stable-bullseye-perl
                snowdreamtech/nginx:1.24-bullseye-perl
                ghcr.io/snowdreamtech/nginx:1.24.0-perl
                ghcr.io/snowdreamtech/nginx:stable-perl
                ghcr.io/snowdreamtech/nginx:1.24-perl
                ghcr.io/snowdreamtech/nginx:1.24.0-bullseye-perl
                ghcr.io/snowdreamtech/nginx:stable-bullseye-perl
                ghcr.io/snowdreamtech/nginx:1.24-bullseye-perl     
            